# Kind cluster configuration for fear-Allah
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 9080
        protocol: TCP
      - containerPort: 8001
        hostPort: 9081
        protocol: TCP
      - containerPort: 9001
        hostPort: 9082
        protocol: TCP
